import type {
  PipelineArtifacts,
  RevisionFeedback,
  UsageInfo,
} from "./types";

export interface RunReportInput {
  caseId: string;
  rawRequest: string;
  artifacts: PipelineArtifacts;
  revisions: RevisionFeedback[];
  usage: Record<string, UsageInfo | undefined>;
  scores?: {
    baseline: number[];
    pipeline: number[];
  };
  generatedAt: string;
}

function counts(artifact: unknown): Record<string, number> {
  if (!artifact || typeof artifact !== "object") return {};
  const a = artifact as Record<string, unknown>;
  const out: Record<string, number> = {};
  if (Array.isArray(a.findings)) out.findings = (a.findings as unknown[]).length;
  if (Array.isArray(a.traceability)) out.traceability = (a.traceability as unknown[]).length;
  if (Array.isArray(a.tests)) out.tests = (a.tests as unknown[]).length;
  if (Array.isArray(a.acceptance_criteria)) out.acceptance_criteria = (a.acceptance_criteria as unknown[]).length;
  if (Array.isArray(a.threat_model)) out.threat_model = (a.threat_model as unknown[]).length;
  return out;
}

function usageLine(u?: UsageInfo): string {
  if (!u) return "—";
  return `${u.model} · ${u.input_tokens} in / ${u.output_tokens} out tokens`;
}

export function buildMarkdownReport(input: RunReportInput): string {
  const { caseId, rawRequest, artifacts, revisions, usage, generatedAt } = input;
  const n2 = artifacts.node2;
  const n3 = artifacts.node3;
  const n4 = artifacts.node4;
  const b = artifacts.baseline;
  const totalTokens = Object.values(usage).reduce(
    (acc, u) => acc + (u?.input_tokens ?? 0) + (u?.output_tokens ?? 0),
    0
  );

  const lines: string[] = [];
  lines.push(`# NodeForge.ai — Run report`);
  lines.push("");
  lines.push(`- **Case:** ${caseId}`);
  lines.push(`- **Raw request:** ${rawRequest}`);
  lines.push(`- **Generated:** ${generatedAt}`);
  lines.push(`- **Total tokens (all model calls):** ${totalTokens}`);
  lines.push("");

  if (b) {
    lines.push(`## Baseline (A — single prompt)`);
    lines.push("");
    lines.push(`Model: ${b.model}`);
    lines.push("");
    lines.push("```");
    lines.push(b.raw_response);
    lines.push("```");
    lines.push("");
  }

  if (n2) {
    lines.push(`## Node 2 — Query Expansion`);
    lines.push("");
    lines.push(`Status: ${n2.status} · usage ${usageLine(usage.node2)}`);
    lines.push(`Acceptance criteria: ${counts(n2).acceptance_criteria}`);
    lines.push(`Threat model items: ${counts(n2).threat_model}`);
    lines.push("");
    lines.push("```json");
    lines.push(JSON.stringify(n2, null, 2));
    lines.push("```");
    lines.push("");
  }

  if (n3) {
    lines.push(`## Node 3 — Execution & Verification`);
    lines.push("");
    lines.push(`Status: ${n3.status} · tests: ${counts(n3).tests} · usage ${usageLine(usage.node3)}`);
    lines.push("");
    lines.push("```json");
    lines.push(JSON.stringify(n3, null, 2));
    lines.push("```");
    lines.push("");
  }

  if (n4) {
    lines.push(`## Node 4 — Output Sanitization (quality gate)`);
    lines.push("");
    lines.push(`Verdict: ${n4.quality_gate} · findings: ${counts(n4).findings} · usage ${usageLine(usage.node4)}`);
    lines.push("");
    lines.push(`> ${n4.final_response?.summary ?? ""}`);
    lines.push("");
    lines.push("```json");
    lines.push(JSON.stringify(n4, null, 2));
    lines.push("```");
    lines.push("");
  }

  if (revisions.length) {
    lines.push(`## Revision loop`);
    lines.push("");
    for (const r of revisions) {
      lines.push(`- **${r.finding_id}** (${r.severity}) → ${r.target}: ${r.description}`);
      lines.push(`  - Correction: ${r.correction}`);
    }
    lines.push("");
  }

  if (input.scores) {
    lines.push(`## Scorecard`);
    lines.push("");
    lines.push(`| Dimension | A — Single prompt | B — Four-node pipeline |`);
    lines.push(`| --- | --- | --- |`);
    const dims = ["Requirement clarity", "Verification", "Security", "Traceability"];
    dims.forEach((d, i) => {
      lines.push(`| ${d} | ${input.scores!.baseline[i]} | ${input.scores!.pipeline[i]} |`);
    });
    lines.push(
      `| **Total / 8** | **${input.scores.baseline.reduce((a, b) => a + b, 0)} / 8** | **${input.scores.pipeline.reduce((a, b) => a + b, 0)} / 8** |`
    );
    lines.push("");
  }

  lines.push("---");
  lines.push("Generated by NodeForge.ai interactive demo.");
  lines.push("");
  return lines.join("\n");
}

export function buildJsonReport(input: RunReportInput): string {
  return JSON.stringify(
    {
      case_id: input.caseId,
      raw_request: input.rawRequest,
      generated_at: input.generatedAt,
      artifacts: input.artifacts,
      revisions: input.revisions,
      usage: input.usage,
      scores: input.scores,
    },
    null,
    2
  );
}

function download(filename: string, content: string, mime = "text/plain") {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function exportMarkdownReport(input: RunReportInput) {
  download(`nodeforge-report-${input.caseId}.md`, buildMarkdownReport(input), "text/markdown");
}

export function exportJsonReport(input: RunReportInput) {
  download(`nodeforge-report-${input.caseId}.json`, buildJsonReport(input), "application/json");
}