/**
 * Markdown reporter: pull-request-comment friendly rendering of a run.
 */

import type { Severity, VerificationRun } from "../core/contracts.js";
import { formatDuration } from "../utils/misc.js";

function severityCounts(findings: readonly { severity: Severity }[]): Record<Severity, number> {
  const counts: Record<Severity, number> = { critical: 0, high: 0, medium: 0, low: 0 };
  for (const finding of findings) counts[finding.severity] += 1;
  return counts;
}

export function renderRunMarkdown(run: VerificationRun): string {
  const lines: string[] = [];
  const target =
    run.request.target.kind === "pull_request"
      ? run.request.target.url ?? "pull request"
      : `${run.request.target.path ?? "unknown"}${run.request.target.ref ? ` @ ${run.request.target.ref}` : ""}`;

  lines.push(`# NodeForge verification report`);
  lines.push("");
  lines.push(`- **Run:** \`${run.id}\` (schema v${run.schemaVersion})`);
  lines.push(`- **Status:** ${run.status}`);
  lines.push(`- **Target:** ${target}`);
  if (run.repository.commitSha) lines.push(`- **Revision:** ${run.repository.commitSha}`);
  lines.push(`- **Mode:** ${run.request.mode}${run.request.dryRun ? " (dry-run)" : ""}`);
  lines.push(`- **Duration:** ${formatDuration(run.durationMs)}`);
  lines.push(`- **Created:** ${run.createdAt}`);
  lines.push("");

  // Findings
  const counts = severityCounts(run.findings);
  lines.push(`## Findings (${run.findings.length})`);
  lines.push("");
  lines.push(
    `critical: ${counts.critical} · high: ${counts.high} · medium: ${counts.medium} · low: ${counts.low}`
  );
  lines.push("");
  if (run.findings.length > 0) {
    lines.push("| ID | Severity | Rule | Location | Message |");
    lines.push("| --- | --- | --- | --- | --- |");
    for (const finding of run.findings) {
      lines.push(
        `| ${finding.id} | ${finding.severity} | ${finding.ruleId} | ${finding.filePath}:${finding.startLine} | ${finding.message} |`
      );
    }
    lines.push("");
    lines.push("### Recommended actions");
    lines.push("");
    for (const finding of run.findings) {
      lines.push(`- **${finding.id}** — ${finding.recommendedAction}`);
    }
    lines.push("");
  } else {
    lines.push("No findings.");
    lines.push("");
  }

  // Tests
  lines.push("## Tests");
  lines.push("");
  const tests = run.testSummary;
  if (!tests) {
    lines.push("Tests were not executed in this run.");
  } else {
    lines.push(`- **Status:** ${tests.status}`);
    lines.push(`- **Runner:** ${tests.runner ?? "none"}`);
    lines.push(`- **Command:** ${tests.command ? `\`${tests.command.join(" ")}\`` : "n/a"}`);
    lines.push(
      `- **Results:** ${tests.passed} passed · ${tests.failed} failed · ${tests.skipped} skipped of ${tests.discovered} discovered`
    );
    lines.push(`- **Exit code:** ${tests.exitCode ?? "n/a"}${tests.timedOut ? " (timed out)" : ""}`);
    lines.push(`- **Network policy:** ${tests.networkPolicy} (${tests.networkEnforcement})`);
    if (tests.reason) lines.push(`- **Note:** ${tests.reason}`);
  }
  lines.push("");

  // Analysis
  if (run.analysis) {
    lines.push("## Analysis");
    lines.push("");
    lines.push(
      `- **Status:** ${run.analysis.status} (provider: ${run.analysis.providerId ?? "none"})`
    );
    lines.push(`- **Note:** ${run.analysis.reason}`);
    lines.push("");
  }

  // Stages
  lines.push("## Stage outcomes");
  lines.push("");
  lines.push("| Stage | Status | Duration | Detail |");
  lines.push("| --- | --- | --- | --- |");
  for (const stage of run.stages) {
    lines.push(
      `| ${stage.stage} | ${stage.status} | ${formatDuration(stage.durationMs)} | ${stage.reason || "—"} |`
    );
  }
  lines.push("");

  if (run.repository.notes.length > 0) {
    lines.push("## Notes");
    lines.push("");
    for (const note of run.repository.notes) lines.push(`- ${note}`);
    lines.push("");
  }

  lines.push("---");
  lines.push(
    `Generated by nodeforge v${run.nodeforgeVersion}. Blocked means verification could not occur; it never implies success.`
  );
  lines.push("");
  return lines.join("\n");
}
